package com.bilgeadam.repository.model;


public enum EGenre {
    DRAMA,KOMEDI, KARAMIZAH, FANTASTIK, ROMANTIK,BILIMKURGU,AKSIYON,ROMANTIKKOMEDI,ANIMASYON,ANIME,MUZIKAL,BELGESEL,BIYOGRAFI,GIZEM, SUC, TARIHI, GERILIM
}