server:
  port: 7070

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/RecommendDb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true